"""
Efficiency of coal plants largely depends on the way they are used. Bentek Energy Company 
made a test, in which they would offset a certain fraction of power supplied by coal plant to wind 
turbine, and the coal plant needed to change the power output. As a result they found cycling up and down
the coal plants results in increased CO2 emissions(even though power output is lower!). The goal of this
exercise, given some initial data and efficiency reduction relation, find the optimal power output 
from wind turbine to reduce emissions(Other than switching the coal plant off completely) 
"""
def efficiency(pw):
    return 0.35-0.00001*(pw**2)
def coal_emissions(e, p_coal):
    return p_coal/e
P_total = 500
eff_dict = {}
for i in range(100):
    p_wind = i
    p_coal = P_total - p_wind
    e = efficiency(p_wind)
    eff_dict.update({p_wind:coal_emissions(e,p_coal)})
    
print('The minimum emissions will be in the case of Wind power of', min(eff_dict.items(), key = lambda x:x[1])[0],'MW.', 'Power, generated by coal will be ', min(eff_dict.items(), key = lambda x:x[1])[1], 'MW. Notice, that even though from coal station we need to only provide 500-P_wind amount of power, it takes so much more power for it to generate due to efficiency being so small.')